// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import (
	mock "github.com/stretchr/testify/mock"

	user "github.com/Confialink/wallet-users/rpc/proto/users"
)

// AuthServiceInterface is an autogenerated mock type for the AuthServiceInterface type
type AuthServiceInterface struct {
	mock.Mock
}

// Can provides a mock function with given fields: role, action, resource
func (_m *AuthServiceInterface) Can(role string, action string, resource string) bool {
	ret := _m.Called(role, action, resource)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = rf(role, action, resource)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// CanDynamic provides a mock function with given fields: _a0, action, resourceName, resource
func (_m *AuthServiceInterface) CanDynamic(_a0 *user.User, action string, resourceName string, resource interface{}) bool {
	ret := _m.Called(_a0, action, resourceName, resource)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*user.User, string, string, interface{}) bool); ok {
		r0 = rf(_a0, action, resourceName, resource)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
