// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import (
	model "github.com/Confialink/wallet-accounts/internal/modules/card/model"
	mock "github.com/stretchr/testify/mock"
)

// CardServiceInterface is an autogenerated mock type for the CardServiceInterface type
type CardServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *CardServiceInterface) Create(_a0 *model.SerializedCard) (*model.Card, error) {
	ret := _m.Called(_a0)

	var r0 *model.Card
	if rf, ok := ret.Get(0).(func(*model.SerializedCard) *model.Card); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Card)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.SerializedCard) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0
func (_m *CardServiceInterface) Get(_a0 uint32) (*model.Card, error) {
	ret := _m.Called(_a0)

	var r0 *model.Card
	if rf, ok := ret.Get(0).(func(uint32) *model.Card); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Card)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint32) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateFields provides a mock function with given fields: _a0, _a1
func (_m *CardServiceInterface) UpdateFields(_a0 uint32, _a1 map[string]interface{}) (*model.Card, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *model.Card
	if rf, ok := ret.Get(0).(func(uint32, map[string]interface{}) *model.Card); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Card)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint32, map[string]interface{}) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
