// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	user "github.com/Confialink/wallet-users/rpc/proto/users"
)

// ContextInterface is an autogenerated mock type for the ContextInterface type
type ContextInterface struct {
	mock.Mock
}

// GetCurrentUser provides a mock function with given fields: c
func (_m *ContextInterface) GetCurrentUser(c *gin.Context) *user.User {
	ret := _m.Called(c)

	var r0 *user.User
	if rf, ok := ret.Get(0).(func(*gin.Context) *user.User); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	return r0
}

// MustGetCurrentUser provides a mock function with given fields: c
func (_m *ContextInterface) MustGetCurrentUser(c *gin.Context) *user.User {
	ret := _m.Called(c)

	var r0 *user.User
	if rf, ok := ret.Get(0).(func(*gin.Context) *user.User); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	return r0
}
