// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/accounts/accounts.proto

package accounts

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DisableCurrencyReq struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableCurrencyReq) Reset()         { *m = DisableCurrencyReq{} }
func (m *DisableCurrencyReq) String() string { return proto.CompactTextString(m) }
func (*DisableCurrencyReq) ProtoMessage()    {}
func (*DisableCurrencyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_621c26192e3dd581, []int{0}
}
func (m *DisableCurrencyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableCurrencyReq.Unmarshal(m, b)
}
func (m *DisableCurrencyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableCurrencyReq.Marshal(b, m, deterministic)
}
func (dst *DisableCurrencyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableCurrencyReq.Merge(dst, src)
}
func (m *DisableCurrencyReq) XXX_Size() int {
	return xxx_messageInfo_DisableCurrencyReq.Size(m)
}
func (m *DisableCurrencyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableCurrencyReq.DiscardUnknown(m)
}

var xxx_messageInfo_DisableCurrencyReq proto.InternalMessageInfo

func (m *DisableCurrencyReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type DisableCurrencyResp struct {
	Can                  bool     `protobuf:"varint,1,opt,name=can,proto3" json:"can,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableCurrencyResp) Reset()         { *m = DisableCurrencyResp{} }
func (m *DisableCurrencyResp) String() string { return proto.CompactTextString(m) }
func (*DisableCurrencyResp) ProtoMessage()    {}
func (*DisableCurrencyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_621c26192e3dd581, []int{1}
}
func (m *DisableCurrencyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableCurrencyResp.Unmarshal(m, b)
}
func (m *DisableCurrencyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableCurrencyResp.Marshal(b, m, deterministic)
}
func (dst *DisableCurrencyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableCurrencyResp.Merge(dst, src)
}
func (m *DisableCurrencyResp) XXX_Size() int {
	return xxx_messageInfo_DisableCurrencyResp.Size(m)
}
func (m *DisableCurrencyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableCurrencyResp.DiscardUnknown(m)
}

var xxx_messageInfo_DisableCurrencyResp proto.InternalMessageInfo

func (m *DisableCurrencyResp) GetCan() bool {
	if m != nil {
		return m.Can
	}
	return false
}

type SettingsByNameReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettingsByNameReq) Reset()         { *m = SettingsByNameReq{} }
func (m *SettingsByNameReq) String() string { return proto.CompactTextString(m) }
func (*SettingsByNameReq) ProtoMessage()    {}
func (*SettingsByNameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_621c26192e3dd581, []int{2}
}
func (m *SettingsByNameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettingsByNameReq.Unmarshal(m, b)
}
func (m *SettingsByNameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettingsByNameReq.Marshal(b, m, deterministic)
}
func (dst *SettingsByNameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettingsByNameReq.Merge(dst, src)
}
func (m *SettingsByNameReq) XXX_Size() int {
	return xxx_messageInfo_SettingsByNameReq.Size(m)
}
func (m *SettingsByNameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SettingsByNameReq.DiscardUnknown(m)
}

var xxx_messageInfo_SettingsByNameReq proto.InternalMessageInfo

func (m *SettingsByNameReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SettingsByNameResp struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettingsByNameResp) Reset()         { *m = SettingsByNameResp{} }
func (m *SettingsByNameResp) String() string { return proto.CompactTextString(m) }
func (*SettingsByNameResp) ProtoMessage()    {}
func (*SettingsByNameResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_621c26192e3dd581, []int{3}
}
func (m *SettingsByNameResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettingsByNameResp.Unmarshal(m, b)
}
func (m *SettingsByNameResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettingsByNameResp.Marshal(b, m, deterministic)
}
func (dst *SettingsByNameResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettingsByNameResp.Merge(dst, src)
}
func (m *SettingsByNameResp) XXX_Size() int {
	return xxx_messageInfo_SettingsByNameResp.Size(m)
}
func (m *SettingsByNameResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SettingsByNameResp.DiscardUnknown(m)
}

var xxx_messageInfo_SettingsByNameResp proto.InternalMessageInfo

func (m *SettingsByNameResp) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type UserHasCardsOrAccountsReq struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserHasCardsOrAccountsReq) Reset()         { *m = UserHasCardsOrAccountsReq{} }
func (m *UserHasCardsOrAccountsReq) String() string { return proto.CompactTextString(m) }
func (*UserHasCardsOrAccountsReq) ProtoMessage()    {}
func (*UserHasCardsOrAccountsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_621c26192e3dd581, []int{4}
}
func (m *UserHasCardsOrAccountsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserHasCardsOrAccountsReq.Unmarshal(m, b)
}
func (m *UserHasCardsOrAccountsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserHasCardsOrAccountsReq.Marshal(b, m, deterministic)
}
func (dst *UserHasCardsOrAccountsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserHasCardsOrAccountsReq.Merge(dst, src)
}
func (m *UserHasCardsOrAccountsReq) XXX_Size() int {
	return xxx_messageInfo_UserHasCardsOrAccountsReq.Size(m)
}
func (m *UserHasCardsOrAccountsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserHasCardsOrAccountsReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserHasCardsOrAccountsReq proto.InternalMessageInfo

func (m *UserHasCardsOrAccountsReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type UserHasCardsOrAccountsResp struct {
	CardsExist           bool     `protobuf:"varint,1,opt,name=cardsExist,proto3" json:"cardsExist,omitempty"`
	AccountsExist        bool     `protobuf:"varint,2,opt,name=accountsExist,proto3" json:"accountsExist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserHasCardsOrAccountsResp) Reset()         { *m = UserHasCardsOrAccountsResp{} }
func (m *UserHasCardsOrAccountsResp) String() string { return proto.CompactTextString(m) }
func (*UserHasCardsOrAccountsResp) ProtoMessage()    {}
func (*UserHasCardsOrAccountsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_621c26192e3dd581, []int{5}
}
func (m *UserHasCardsOrAccountsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserHasCardsOrAccountsResp.Unmarshal(m, b)
}
func (m *UserHasCardsOrAccountsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserHasCardsOrAccountsResp.Marshal(b, m, deterministic)
}
func (dst *UserHasCardsOrAccountsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserHasCardsOrAccountsResp.Merge(dst, src)
}
func (m *UserHasCardsOrAccountsResp) XXX_Size() int {
	return xxx_messageInfo_UserHasCardsOrAccountsResp.Size(m)
}
func (m *UserHasCardsOrAccountsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserHasCardsOrAccountsResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserHasCardsOrAccountsResp proto.InternalMessageInfo

func (m *UserHasCardsOrAccountsResp) GetCardsExist() bool {
	if m != nil {
		return m.CardsExist
	}
	return false
}

func (m *UserHasCardsOrAccountsResp) GetAccountsExist() bool {
	if m != nil {
		return m.AccountsExist
	}
	return false
}

type GenerateAndSendTansReq struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateAndSendTansReq) Reset()         { *m = GenerateAndSendTansReq{} }
func (m *GenerateAndSendTansReq) String() string { return proto.CompactTextString(m) }
func (*GenerateAndSendTansReq) ProtoMessage()    {}
func (*GenerateAndSendTansReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_621c26192e3dd581, []int{6}
}
func (m *GenerateAndSendTansReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAndSendTansReq.Unmarshal(m, b)
}
func (m *GenerateAndSendTansReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAndSendTansReq.Marshal(b, m, deterministic)
}
func (dst *GenerateAndSendTansReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAndSendTansReq.Merge(dst, src)
}
func (m *GenerateAndSendTansReq) XXX_Size() int {
	return xxx_messageInfo_GenerateAndSendTansReq.Size(m)
}
func (m *GenerateAndSendTansReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAndSendTansReq.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAndSendTansReq proto.InternalMessageInfo

func (m *GenerateAndSendTansReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GenerateAndSendTansResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateAndSendTansResp) Reset()         { *m = GenerateAndSendTansResp{} }
func (m *GenerateAndSendTansResp) String() string { return proto.CompactTextString(m) }
func (*GenerateAndSendTansResp) ProtoMessage()    {}
func (*GenerateAndSendTansResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_621c26192e3dd581, []int{7}
}
func (m *GenerateAndSendTansResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAndSendTansResp.Unmarshal(m, b)
}
func (m *GenerateAndSendTansResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAndSendTansResp.Marshal(b, m, deterministic)
}
func (dst *GenerateAndSendTansResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAndSendTansResp.Merge(dst, src)
}
func (m *GenerateAndSendTansResp) XXX_Size() int {
	return xxx_messageInfo_GenerateAndSendTansResp.Size(m)
}
func (m *GenerateAndSendTansResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAndSendTansResp.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAndSendTansResp proto.InternalMessageInfo

type GenerateAccountReq struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CurrencyCode         string   `protobuf:"bytes,2,opt,name=currencyCode,proto3" json:"currencyCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateAccountReq) Reset()         { *m = GenerateAccountReq{} }
func (m *GenerateAccountReq) String() string { return proto.CompactTextString(m) }
func (*GenerateAccountReq) ProtoMessage()    {}
func (*GenerateAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_621c26192e3dd581, []int{8}
}
func (m *GenerateAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAccountReq.Unmarshal(m, b)
}
func (m *GenerateAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAccountReq.Marshal(b, m, deterministic)
}
func (dst *GenerateAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAccountReq.Merge(dst, src)
}
func (m *GenerateAccountReq) XXX_Size() int {
	return xxx_messageInfo_GenerateAccountReq.Size(m)
}
func (m *GenerateAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAccountReq proto.InternalMessageInfo

func (m *GenerateAccountReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GenerateAccountReq) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

type GenerateAccountResp struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number               string   `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateAccountResp) Reset()         { *m = GenerateAccountResp{} }
func (m *GenerateAccountResp) String() string { return proto.CompactTextString(m) }
func (*GenerateAccountResp) ProtoMessage()    {}
func (*GenerateAccountResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_621c26192e3dd581, []int{9}
}
func (m *GenerateAccountResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAccountResp.Unmarshal(m, b)
}
func (m *GenerateAccountResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAccountResp.Marshal(b, m, deterministic)
}
func (dst *GenerateAccountResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAccountResp.Merge(dst, src)
}
func (m *GenerateAccountResp) XXX_Size() int {
	return xxx_messageInfo_GenerateAccountResp.Size(m)
}
func (m *GenerateAccountResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAccountResp.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAccountResp proto.InternalMessageInfo

func (m *GenerateAccountResp) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GenerateAccountResp) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func init() {
	proto.RegisterType((*DisableCurrencyReq)(nil), "velmie.wallet.accounts.DisableCurrencyReq")
	proto.RegisterType((*DisableCurrencyResp)(nil), "velmie.wallet.accounts.DisableCurrencyResp")
	proto.RegisterType((*SettingsByNameReq)(nil), "velmie.wallet.accounts.SettingsByNameReq")
	proto.RegisterType((*SettingsByNameResp)(nil), "velmie.wallet.accounts.SettingsByNameResp")
	proto.RegisterType((*UserHasCardsOrAccountsReq)(nil), "velmie.wallet.accounts.UserHasCardsOrAccountsReq")
	proto.RegisterType((*UserHasCardsOrAccountsResp)(nil), "velmie.wallet.accounts.UserHasCardsOrAccountsResp")
	proto.RegisterType((*GenerateAndSendTansReq)(nil), "velmie.wallet.accounts.GenerateAndSendTansReq")
	proto.RegisterType((*GenerateAndSendTansResp)(nil), "velmie.wallet.accounts.GenerateAndSendTansResp")
	proto.RegisterType((*GenerateAccountReq)(nil), "velmie.wallet.accounts.GenerateAccountReq")
	proto.RegisterType((*GenerateAccountResp)(nil), "velmie.wallet.accounts.GenerateAccountResp")
}

func init() {
	proto.RegisterFile("rpc/accounts/accounts.proto", fileDescriptor_accounts_621c26192e3dd581)
}

var fileDescriptor_accounts_621c26192e3dd581 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x95, 0x34, 0x54, 0x65, 0xc4, 0x9f, 0x66, 0x8a, 0x42, 0x6b, 0x24, 0x84, 0x56, 0x48,
	0x2d, 0x41, 0xb8, 0xa2, 0x9c, 0x39, 0x34, 0x01, 0x15, 0x71, 0x00, 0x94, 0xc2, 0x85, 0xdb, 0x66,
	0x3d, 0x42, 0x46, 0xf6, 0x7a, 0xd9, 0x59, 0x07, 0x72, 0xe4, 0x4b, 0xf2, 0x79, 0x90, 0x9d, 0x75,
	0xda, 0xc4, 0x5e, 0xa9, 0xbd, 0xcd, 0xce, 0xbc, 0x7d, 0x5a, 0xcf, 0xfb, 0xc9, 0xf0, 0xc4, 0x1a,
	0x75, 0x2a, 0x95, 0x2a, 0x4a, 0xed, 0x78, 0x5d, 0xc4, 0xc6, 0x16, 0xae, 0xc0, 0xd1, 0x82, 0xb2,
	0x3c, 0xa5, 0xf8, 0xb7, 0xcc, 0x32, 0x72, 0x71, 0x33, 0x15, 0x27, 0x80, 0xef, 0x52, 0x96, 0xf3,
	0x8c, 0xa6, 0xa5, 0xb5, 0xa4, 0xd5, 0x72, 0x46, 0xbf, 0x10, 0x61, 0xa0, 0x8a, 0x84, 0x0e, 0x7b,
	0xcf, 0x7a, 0x27, 0x77, 0x67, 0x75, 0x2d, 0x8e, 0xe1, 0xa0, 0xa5, 0x64, 0x83, 0xfb, 0xb0, 0xa3,
	0xa4, 0xae, 0x95, 0x7b, 0xb3, 0xaa, 0x14, 0xc7, 0x30, 0xbc, 0x24, 0xe7, 0x52, 0xfd, 0x83, 0x27,
	0xcb, 0x4f, 0x32, 0x27, 0xef, 0xa8, 0x65, 0xbe, 0x76, 0xac, 0x6a, 0x31, 0x06, 0xdc, 0x16, 0xb2,
	0xc1, 0x47, 0x70, 0x67, 0x21, 0xb3, 0xb2, 0x91, 0xae, 0x0e, 0xe2, 0x15, 0x1c, 0x7d, 0x63, 0xb2,
	0x1f, 0x24, 0x4f, 0xa5, 0x4d, 0xf8, 0xb3, 0x3d, 0xf7, 0x5f, 0x50, 0x99, 0xef, 0xc3, 0x4e, 0x99,
	0x26, 0xfe, 0x42, 0x55, 0x8a, 0x39, 0x44, 0x21, 0x39, 0x1b, 0x7c, 0x0a, 0xa0, 0xaa, 0xf6, 0xfb,
	0x3f, 0x29, 0x3b, 0xff, 0xf4, 0x6b, 0x1d, 0x7c, 0x0e, 0xf7, 0x9b, 0x05, 0xad, 0x24, 0xfd, 0x5a,
	0xb2, 0xd9, 0x14, 0x63, 0x18, 0x5d, 0x90, 0x26, 0x2b, 0x1d, 0x9d, 0xeb, 0xe4, 0x92, 0x74, 0xf2,
	0x55, 0xea, 0xc0, 0x7b, 0x8e, 0xe0, 0x71, 0xa7, 0x96, 0x8d, 0xf8, 0x08, 0xb8, 0x1e, 0xad, 0xfc,
	0x3b, 0x2d, 0x50, 0xc0, 0x3d, 0xe5, 0x17, 0x3f, 0xad, 0xb2, 0xe9, 0xd7, 0xa3, 0x8d, 0x9e, 0x78,
	0x0b, 0x07, 0x2d, 0x2f, 0x36, 0xf8, 0x00, 0xfa, 0xde, 0x6b, 0x30, 0xeb, 0xa7, 0x09, 0x8e, 0x60,
	0x57, 0x97, 0xf9, 0x9c, 0xac, 0x37, 0xf1, 0xa7, 0xb3, 0x7f, 0x03, 0x18, 0x36, 0x8b, 0xfa, 0x62,
	0x0b, 0x45, 0xcc, 0x85, 0xc5, 0x1c, 0x70, 0x2a, 0xf5, 0x56, 0xf6, 0x38, 0x8e, 0xbb, 0x89, 0x8a,
	0xdb, 0x38, 0x45, 0x2f, 0x6f, 0xac, 0x65, 0x83, 0x3f, 0x61, 0x78, 0x41, 0x6e, 0x13, 0x0c, 0x7c,
	0x11, 0x72, 0x68, 0x91, 0x16, 0x8d, 0x6f, 0x2a, 0x65, 0x83, 0x7f, 0x7b, 0x70, 0xd8, 0xcd, 0xc9,
	0x64, 0x89, 0xaf, 0x43, 0x46, 0x41, 0x10, 0xa3, 0xb3, 0xdb, 0x5e, 0x61, 0x83, 0x8b, 0x6b, 0x99,
	0x5d, 0xa1, 0x81, 0x71, 0xc8, 0xaa, 0x9b, 0xb9, 0xe8, 0xf4, 0x56, 0xfa, 0x7a, 0xcf, 0x0f, 0xb7,
	0x58, 0x09, 0x67, 0xda, 0x06, 0x34, 0x9c, 0x69, 0x07, 0x80, 0x13, 0xf8, 0xbe, 0xd7, 0xcc, 0xe7,
	0xbb, 0xf5, 0x0f, 0xe9, 0xcd, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x73, 0x60, 0x9a, 0x0f, 0xaf,
	0x04, 0x00, 0x00,
}
