// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/limit/limit.proto

package limit

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LimitName int32

const (
	// empty limit name means "no name" it could be used for "Get" requests
	LimitName_EMPTY LimitName = 0
	// aggregation of all accounts balances
	LimitName_MAX_TOTAL_BALANCE LimitName = 1
	// maximum value that can be credited within a single transfer
	LimitName_MAX_CREDIT_PER_TRANSFER LimitName = 2
	// maximum value that can be debited within a single transfer
	LimitName_MAX_DEBIT_PER_TRANSFER LimitName = 3
	// aggregation of all debit transactions for the current day
	LimitName_MAX_TOTAL_DEBIT_PER_DAY LimitName = 4
	// aggregation of all debit transactions for the current month
	LimitName_MAX_TOTAL_DEBIT_PER_MONTH LimitName = 5
)

var LimitName_name = map[int32]string{
	0: "EMPTY",
	1: "MAX_TOTAL_BALANCE",
	2: "MAX_CREDIT_PER_TRANSFER",
	3: "MAX_DEBIT_PER_TRANSFER",
	4: "MAX_TOTAL_DEBIT_PER_DAY",
	5: "MAX_TOTAL_DEBIT_PER_MONTH",
}

var LimitName_value = map[string]int32{
	"EMPTY":                     0,
	"MAX_TOTAL_BALANCE":         1,
	"MAX_CREDIT_PER_TRANSFER":   2,
	"MAX_DEBIT_PER_TRANSFER":    3,
	"MAX_TOTAL_DEBIT_PER_DAY":   4,
	"MAX_TOTAL_DEBIT_PER_MONTH": 5,
}

func (x LimitName) String() string {
	return proto.EnumName(LimitName_name, int32(x))
}

func (LimitName) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_53a6293df50f056a, []int{0}
}

// Limit represents limit
type Limit struct {
	// currency code might be empty string if limit is not exist or "no limit"
	CurrencyCode string `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	// amount is decimal string representation of limit amount
	// might be empty string if limit is not exist or "no limit"
	Amount string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// indicates whether a limit is exist
	Exists bool `protobuf:"varint,3,opt,name=exists,proto3" json:"exists,omitempty"`
	// indicates that it is not limited
	NoLimit              bool     `protobuf:"varint,4,opt,name=no_limit,json=noLimit,proto3" json:"no_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Limit) Reset()         { *m = Limit{} }
func (m *Limit) String() string { return proto.CompactTextString(m) }
func (*Limit) ProtoMessage()    {}
func (*Limit) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a6293df50f056a, []int{0}
}

func (m *Limit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Limit.Unmarshal(m, b)
}
func (m *Limit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Limit.Marshal(b, m, deterministic)
}
func (m *Limit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Limit.Merge(m, src)
}
func (m *Limit) XXX_Size() int {
	return xxx_messageInfo_Limit.Size(m)
}
func (m *Limit) XXX_DiscardUnknown() {
	xxx_messageInfo_Limit.DiscardUnknown(m)
}

var xxx_messageInfo_Limit proto.InternalMessageInfo

func (m *Limit) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *Limit) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Limit) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *Limit) GetNoLimit() bool {
	if m != nil {
		return m.NoLimit
	}
	return false
}

// LimitId identifies limit
type LimitId struct {
	// specific limit name
	Name LimitName `protobuf:"varint,1,opt,name=name,proto3,enum=velmie.wallet.accounts.LimitName" json:"name,omitempty"`
	// entity (relation name) e.g. user
	Entity string `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	// unique identifier of the entity
	EntityId             string   `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LimitId) Reset()         { *m = LimitId{} }
func (m *LimitId) String() string { return proto.CompactTextString(m) }
func (*LimitId) ProtoMessage()    {}
func (*LimitId) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a6293df50f056a, []int{1}
}

func (m *LimitId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LimitId.Unmarshal(m, b)
}
func (m *LimitId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LimitId.Marshal(b, m, deterministic)
}
func (m *LimitId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LimitId.Merge(m, src)
}
func (m *LimitId) XXX_Size() int {
	return xxx_messageInfo_LimitId.Size(m)
}
func (m *LimitId) XXX_DiscardUnknown() {
	xxx_messageInfo_LimitId.DiscardUnknown(m)
}

var xxx_messageInfo_LimitId proto.InternalMessageInfo

func (m *LimitId) GetName() LimitName {
	if m != nil {
		return m.Name
	}
	return LimitName_EMPTY
}

func (m *LimitId) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func (m *LimitId) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

type LimitWithId struct {
	Limit                *Limit   `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	LimitId              *LimitId `protobuf:"bytes,2,opt,name=limit_id,json=limitId,proto3" json:"limit_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LimitWithId) Reset()         { *m = LimitWithId{} }
func (m *LimitWithId) String() string { return proto.CompactTextString(m) }
func (*LimitWithId) ProtoMessage()    {}
func (*LimitWithId) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a6293df50f056a, []int{2}
}

func (m *LimitWithId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LimitWithId.Unmarshal(m, b)
}
func (m *LimitWithId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LimitWithId.Marshal(b, m, deterministic)
}
func (m *LimitWithId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LimitWithId.Merge(m, src)
}
func (m *LimitWithId) XXX_Size() int {
	return xxx_messageInfo_LimitWithId.Size(m)
}
func (m *LimitWithId) XXX_DiscardUnknown() {
	xxx_messageInfo_LimitWithId.DiscardUnknown(m)
}

var xxx_messageInfo_LimitWithId proto.InternalMessageInfo

func (m *LimitWithId) GetLimit() *Limit {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *LimitWithId) GetLimitId() *LimitId {
	if m != nil {
		return m.LimitId
	}
	return nil
}

type SetLimitsRequest struct {
	Limits               []*LimitWithId `protobuf:"bytes,1,rep,name=limits,proto3" json:"limits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetLimitsRequest) Reset()         { *m = SetLimitsRequest{} }
func (m *SetLimitsRequest) String() string { return proto.CompactTextString(m) }
func (*SetLimitsRequest) ProtoMessage()    {}
func (*SetLimitsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a6293df50f056a, []int{3}
}

func (m *SetLimitsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLimitsRequest.Unmarshal(m, b)
}
func (m *SetLimitsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLimitsRequest.Marshal(b, m, deterministic)
}
func (m *SetLimitsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLimitsRequest.Merge(m, src)
}
func (m *SetLimitsRequest) XXX_Size() int {
	return xxx_messageInfo_SetLimitsRequest.Size(m)
}
func (m *SetLimitsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLimitsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetLimitsRequest proto.InternalMessageInfo

func (m *SetLimitsRequest) GetLimits() []*LimitWithId {
	if m != nil {
		return m.Limits
	}
	return nil
}

type SetLimitsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetLimitsResponse) Reset()         { *m = SetLimitsResponse{} }
func (m *SetLimitsResponse) String() string { return proto.CompactTextString(m) }
func (*SetLimitsResponse) ProtoMessage()    {}
func (*SetLimitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a6293df50f056a, []int{4}
}

func (m *SetLimitsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLimitsResponse.Unmarshal(m, b)
}
func (m *SetLimitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLimitsResponse.Marshal(b, m, deterministic)
}
func (m *SetLimitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLimitsResponse.Merge(m, src)
}
func (m *SetLimitsResponse) XXX_Size() int {
	return xxx_messageInfo_SetLimitsResponse.Size(m)
}
func (m *SetLimitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLimitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetLimitsResponse proto.InternalMessageInfo

type GetLimitsRequest struct {
	Identifiers          []*LimitId `protobuf:"bytes,1,rep,name=identifiers,proto3" json:"identifiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetLimitsRequest) Reset()         { *m = GetLimitsRequest{} }
func (m *GetLimitsRequest) String() string { return proto.CompactTextString(m) }
func (*GetLimitsRequest) ProtoMessage()    {}
func (*GetLimitsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a6293df50f056a, []int{5}
}

func (m *GetLimitsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLimitsRequest.Unmarshal(m, b)
}
func (m *GetLimitsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLimitsRequest.Marshal(b, m, deterministic)
}
func (m *GetLimitsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLimitsRequest.Merge(m, src)
}
func (m *GetLimitsRequest) XXX_Size() int {
	return xxx_messageInfo_GetLimitsRequest.Size(m)
}
func (m *GetLimitsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLimitsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLimitsRequest proto.InternalMessageInfo

func (m *GetLimitsRequest) GetIdentifiers() []*LimitId {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

type GetLimitsResponse struct {
	Limits               []*LimitWithId `protobuf:"bytes,1,rep,name=limits,proto3" json:"limits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetLimitsResponse) Reset()         { *m = GetLimitsResponse{} }
func (m *GetLimitsResponse) String() string { return proto.CompactTextString(m) }
func (*GetLimitsResponse) ProtoMessage()    {}
func (*GetLimitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a6293df50f056a, []int{6}
}

func (m *GetLimitsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLimitsResponse.Unmarshal(m, b)
}
func (m *GetLimitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLimitsResponse.Marshal(b, m, deterministic)
}
func (m *GetLimitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLimitsResponse.Merge(m, src)
}
func (m *GetLimitsResponse) XXX_Size() int {
	return xxx_messageInfo_GetLimitsResponse.Size(m)
}
func (m *GetLimitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLimitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLimitsResponse proto.InternalMessageInfo

func (m *GetLimitsResponse) GetLimits() []*LimitWithId {
	if m != nil {
		return m.Limits
	}
	return nil
}

type ResetLimitsRequest struct {
	Identifiers          []*LimitId `protobuf:"bytes,1,rep,name=identifiers,proto3" json:"identifiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ResetLimitsRequest) Reset()         { *m = ResetLimitsRequest{} }
func (m *ResetLimitsRequest) String() string { return proto.CompactTextString(m) }
func (*ResetLimitsRequest) ProtoMessage()    {}
func (*ResetLimitsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a6293df50f056a, []int{7}
}

func (m *ResetLimitsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetLimitsRequest.Unmarshal(m, b)
}
func (m *ResetLimitsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetLimitsRequest.Marshal(b, m, deterministic)
}
func (m *ResetLimitsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetLimitsRequest.Merge(m, src)
}
func (m *ResetLimitsRequest) XXX_Size() int {
	return xxx_messageInfo_ResetLimitsRequest.Size(m)
}
func (m *ResetLimitsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetLimitsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetLimitsRequest proto.InternalMessageInfo

func (m *ResetLimitsRequest) GetIdentifiers() []*LimitId {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

type ResetLimitsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetLimitsResponse) Reset()         { *m = ResetLimitsResponse{} }
func (m *ResetLimitsResponse) String() string { return proto.CompactTextString(m) }
func (*ResetLimitsResponse) ProtoMessage()    {}
func (*ResetLimitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a6293df50f056a, []int{8}
}

func (m *ResetLimitsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetLimitsResponse.Unmarshal(m, b)
}
func (m *ResetLimitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetLimitsResponse.Marshal(b, m, deterministic)
}
func (m *ResetLimitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetLimitsResponse.Merge(m, src)
}
func (m *ResetLimitsResponse) XXX_Size() int {
	return xxx_messageInfo_ResetLimitsResponse.Size(m)
}
func (m *ResetLimitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetLimitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetLimitsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("velmie.wallet.accounts.LimitName", LimitName_name, LimitName_value)
	proto.RegisterType((*Limit)(nil), "velmie.wallet.accounts.Limit")
	proto.RegisterType((*LimitId)(nil), "velmie.wallet.accounts.LimitId")
	proto.RegisterType((*LimitWithId)(nil), "velmie.wallet.accounts.LimitWithId")
	proto.RegisterType((*SetLimitsRequest)(nil), "velmie.wallet.accounts.SetLimitsRequest")
	proto.RegisterType((*SetLimitsResponse)(nil), "velmie.wallet.accounts.SetLimitsResponse")
	proto.RegisterType((*GetLimitsRequest)(nil), "velmie.wallet.accounts.GetLimitsRequest")
	proto.RegisterType((*GetLimitsResponse)(nil), "velmie.wallet.accounts.GetLimitsResponse")
	proto.RegisterType((*ResetLimitsRequest)(nil), "velmie.wallet.accounts.ResetLimitsRequest")
	proto.RegisterType((*ResetLimitsResponse)(nil), "velmie.wallet.accounts.ResetLimitsResponse")
}

func init() {
	proto.RegisterFile("rpc/limit/limit.proto", fileDescriptor_53a6293df50f056a)
}

var fileDescriptor_53a6293df50f056a = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x54, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0x26, 0xef, 0x78, 0x02, 0x95, 0xb3, 0x55, 0x42, 0x1a, 0x54, 0x01, 0xee, 0xa5, 0x14, 0xc9,
	0x48, 0xa9, 0xb8, 0xc0, 0xc9, 0x49, 0x4c, 0x88, 0x94, 0x97, 0xb6, 0x46, 0xa5, 0xbd, 0x58, 0xc6,
	0xde, 0x8a, 0x95, 0x1c, 0x3b, 0xd8, 0x6b, 0x4a, 0x2f, 0xfc, 0x18, 0xae, 0xfc, 0x49, 0xf6, 0x91,
	0x40, 0x49, 0xdb, 0x10, 0x09, 0xf5, 0x12, 0xcd, 0xce, 0x7c, 0xaf, 0xec, 0x4e, 0x02, 0x8d, 0x64,
	0xe1, 0xbf, 0x0a, 0xe9, 0x9c, 0x32, 0xf5, 0x69, 0x2e, 0x92, 0x98, 0xc5, 0xa8, 0xf9, 0x95, 0x84,
	0x73, 0x4a, 0xcc, 0x4b, 0x2f, 0x0c, 0x09, 0x33, 0x3d, 0xdf, 0x8f, 0xb3, 0x88, 0xa5, 0xc6, 0x25,
	0x94, 0x46, 0x02, 0x86, 0x0e, 0xe0, 0x91, 0x9f, 0x25, 0x09, 0x89, 0xfc, 0x2b, 0xd7, 0x8f, 0x03,
	0xd2, 0xca, 0x3d, 0xcb, 0x1d, 0x6a, 0xf8, 0xe1, 0xaa, 0xd9, 0xe3, 0x3d, 0xd4, 0x84, 0xb2, 0x37,
	0x17, 0xc4, 0x56, 0x5e, 0x4e, 0x97, 0x27, 0xd1, 0x27, 0xdf, 0x68, 0xca, 0xd2, 0x56, 0x81, 0xf7,
	0xab, 0x78, 0x79, 0x42, 0x7b, 0x50, 0x8d, 0x62, 0x57, 0xe6, 0x68, 0x15, 0xe5, 0xa4, 0x12, 0xc5,
	0xd2, 0xcf, 0xc8, 0xa0, 0x22, 0x8b, 0x61, 0x80, 0x5e, 0x43, 0x31, 0xf2, 0xe6, 0xca, 0x71, 0xa7,
	0xf3, 0xdc, 0xbc, 0x3d, 0xaa, 0x29, 0xe1, 0x13, 0x0e, 0xc4, 0x12, 0x2e, 0x4d, 0x23, 0x46, 0xd9,
	0xd5, 0x2a, 0x8c, 0x3a, 0xa1, 0x27, 0xa0, 0xa9, 0xca, 0xa5, 0x81, 0xcc, 0xa3, 0xe1, 0xaa, 0x6a,
	0x0c, 0x03, 0xe3, 0x3b, 0xd4, 0xa4, 0xce, 0x29, 0x65, 0x9f, 0xb9, 0xf5, 0x31, 0x94, 0x54, 0x3a,
	0xe1, 0x5d, 0xeb, 0xec, 0x6f, 0xf4, 0xc6, 0x0a, 0x8b, 0xde, 0x40, 0x55, 0x16, 0x42, 0x3f, 0x2f,
	0x79, 0x4f, 0x37, 0xf2, 0x86, 0x01, 0xae, 0x84, 0xaa, 0x30, 0xa6, 0xa0, 0x9f, 0x10, 0x26, 0xdb,
	0x29, 0x26, 0x5f, 0x32, 0x92, 0x32, 0xf4, 0x16, 0xca, 0x72, 0x9c, 0xf2, 0x14, 0x05, 0xae, 0x76,
	0xb0, 0x51, 0x4d, 0x25, 0xc7, 0x4b, 0x8a, 0xb1, 0x0b, 0xf5, 0x6b, 0x82, 0xe9, 0x22, 0x8e, 0x52,
	0x62, 0x7c, 0x00, 0x7d, 0xb0, 0xee, 0x62, 0x41, 0x8d, 0x06, 0xe2, 0x1e, 0x2e, 0x28, 0x49, 0x56,
	0x56, 0xff, 0x0c, 0x7e, 0x9d, 0x63, 0xcc, 0xa0, 0x3e, 0x58, 0xf7, 0xfa, 0xbf, 0xf4, 0xa7, 0x80,
	0xb8, 0xd0, 0x3d, 0x44, 0x6d, 0xc0, 0xee, 0x5f, 0xc2, 0x2a, 0xec, 0xd1, 0x8f, 0x1c, 0x68, 0xbf,
	0xf7, 0x08, 0x69, 0x50, 0xb2, 0xc7, 0x33, 0xe7, 0x4c, 0x7f, 0x80, 0x1a, 0x50, 0x1f, 0x5b, 0x1f,
	0x5d, 0x67, 0xea, 0x58, 0x23, 0xb7, 0x6b, 0x8d, 0xac, 0x49, 0xcf, 0xd6, 0x73, 0x7c, 0x97, 0x1e,
	0x8b, 0x76, 0x0f, 0xdb, 0xfd, 0xa1, 0xe3, 0xce, 0x6c, 0xec, 0x3a, 0xd8, 0x9a, 0x9c, 0xbc, 0xb3,
	0xb1, 0x9e, 0x47, 0x6d, 0x68, 0x8a, 0x61, 0xdf, 0xee, 0xae, 0xcf, 0x0a, 0x2b, 0xa2, 0xd2, 0xfb,
	0x83, 0xe8, 0x5b, 0x67, 0x7a, 0x11, 0xed, 0xc3, 0xde, 0x6d, 0xc3, 0xf1, 0x74, 0xe2, 0xbc, 0xd7,
	0x4b, 0x9d, 0x9f, 0x79, 0x28, 0xab, 0xdc, 0xe8, 0x1c, 0x0a, 0xfc, 0x75, 0xd1, 0xe1, 0x5d, 0xdf,
	0x7d, 0x7d, 0x97, 0xda, 0x2f, 0xb6, 0x40, 0x2e, 0x1f, 0x8e, 0x6b, 0x0f, 0x36, 0x69, 0x0f, 0xb6,
	0xd6, 0xbe, 0xb9, 0x14, 0x14, 0x76, 0xe4, 0xf5, 0x3b, 0x71, 0x9f, 0x5c, 0x78, 0x59, 0xc8, 0xd0,
	0xd1, 0x5d, 0xe4, 0x9b, 0xef, 0xdf, 0x7e, 0xb9, 0x15, 0x56, 0x59, 0x75, 0x2b, 0xe7, 0xea, 0x67,
	0xf9, 0xa9, 0x2c, 0xff, 0xe9, 0x8e, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xb9, 0x46, 0x21,
	0x02, 0x05, 0x00, 0x00,
}
