name: Linter

on:
  push:
    branches:
      '**'
jobs:
  linter:
    name: Running linter
    runs-on: ubuntu-latest
    container:
      image: golangci/golangci-lint:v1.27-alpine
      env:
        REPOSITORY_PRIVATE_KEY: ${{ secrets.REPOSITORY_PRIVATE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup repository key
        run: ./ci/setup-repository-private-key.sh
      - name: Print key
        run: echo "${REPOSITORY_PRIVATE_KEY}"
      - name: Run linter
        run: golangci-lint run --new-from-rev=dacf3b65c988250c6f7bd96874deb16a1fa80bba --color always --disable-all -E gofmt -E deadcode -E errcheck -E gosimple -E govet -E ineffassign -E staticcheck -E structcheck -E typecheck -E varcheck
  test:
    name: Running test
    runs-on: ubuntu-latest
    container:
      image: golang:1.14-alpine
      env:
        CGO_ENABLED: 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup repository key
        run: ./ci/setup-repository-private-key.sh

      - name: Run test
        run: go test -cover ./...



